CREATE TABLE IF NOT EXISTS public.planner_gap_analysis_reply (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id integer NOT NULL REFERENCES public.planner_task(id) ON DELETE CASCADE,
    gpt_file_id text NOT NULL,
    gap_analysis text NOT NULL DEFAULT '',
    clarification_email text NOT NULL DEFAULT '',
    extractor_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_on timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_planner_gap_analysis_reply_task_id
    ON public.planner_gap_analysis_reply(task_id);
